version: '3.5'
services:
  blog:
      image: tomhjx/hexo:centos7.5.2.0.20201207195256
      command: ["hexo", "server", "--debug"]
      restart: always
      ports:
        - "4000:4000"
      volumes:
        - ./uploads:/var/www/blog/themes/next/source/uploads
        - ./themes/next/_config.yml:/var/www/blog/themes/next/_config.yml
        - ./_config.yml:/var/www/blog/_config.yml
        - ./scaffolds:/var/www/blog/scaffolds
        - ./source:/var/www/blog/source
        - /Users/tom/.ssh/id_rsa:/root/.ssh/id_rsa
        - /Users/tom/.gitconfig:/root/.gitconfig